version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    container_name: elasticsearch
    volumes:
#      - ./elasticsearch/config:/usr/share/elasticsearch/config/
#      - ./elasticsearch/config:/etc/elasticsearch/config
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g -XX:ParallelGCThreads=2 -Dlog4j2.disable.jmx=true"
#      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -XX:ParallelGCThreads=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
#    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    networks:
      - elk

  logstash:
    build: logstash/
    container_name: logstash-redis
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    container_name: kibana
    volumes:
      - ./kibana/config:/etc/kibana/
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://192.168.100.194:9200
    networks:
      - elk
    depends_on:
      - elasticsearch

  redis:
    image: redis:3
    container_name: redis
    volumes:
      - /usr/share/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  es-data:
    driver: local

networks:
  elk:
    driver: bridge
