version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - elkr

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xms2g -Xmx2g"
    networks:
      - elkr
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elkr
    depends_on:
      - elasticsearch

  redis:
    image: redis:3
    container_name: redis
    volumes:
      - /usr/share/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - elkr
    depends_on:
      - elasticsearch

networks:
  elkr:
    driver: bridge
